roi:
  image_h: 900
  image_w: 1600
  polygon:
  - !!python/tuple
    - 217
    - 898
  - !!python/tuple
    - 780
    - 457
  - !!python/tuple
    - 825
    - 457
  - !!python/tuple
    - 1465
    - 897
  x1: 217
  x1_norm: 0.1356
  x2: 1465
  x2_norm: 0.9156
  y1: 457
  y1_norm: 0.5078
  y2: 898
  y2_norm: 0.9978
